[package]
name = "imview"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui_extras = { version = "0.29", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png", "webp"] }
rfd = "0.15"